### ISSUE TITLE
File not uploading

### ISSUE THREAD

**Issue by gebdu** [alperuzun/VGC#1]

**Comment by evatosco** [comment]
Hi!
I'm using the current version of VGC for Windows 11. I already meet the requirements for Java (as far as I'm concerned). I was trying to load a VCF (pretty big, full of annotation info, hundreds of samples) to VGC (hg19 genomic reference), and it changed the interface for a few seconds, right before returning to the program's starting page/aspect. I thought that I exceeded the requirements so I tried with only chr1 of the same VCF. Same response. Then I tried with a much much smaller multisample toy VCF, and then with a 1 sample toy VCF. Same response. I feel like the software is trying to read the file but halts for some reason. Do you have any idea of what's happening? Can I fix it myself?

I would really appreciate some help to dig a little bit and find some error code or something similar. I can't say much more about this issue because no error logs show up. Sorry...

This isn't urgent, I was just trying it out, this tool looks very promising.
Please feel free to ask for more details if needed.

Thank you for developing this tool and thanks for the help!
Eva

**Comment by alperuzun** [comment]
Dear Eva, 

Thank you very much for your email.
It may be because of VCF format but if you don't mind, could it be possible to provide a toy example that we can test on other OS and see what is going on with the application's behaviour in the backend?

Thank you
Alper

**Comment by evatosco** [comment]
Hi Alper! Thank you for your answer!

Sure, no problem.
I attached the VCF files here in a WeTransfer link (valid for 7 days from now: [link deleted]) because of GitHub restrictions on uploading files (I know it looks like a virus but please trust me on this :/ ).
I tried all 3 VCFs (uncompressed) in VGC, with no apparent change in response of the interface.

Please remember to unzip (gzip) them before you test them to get them in .vcf extensions.
Thanks! I hope it helps!

**Comment by alperuzun** [comment]
Hi Eva,

Thank you very much for providing the files.
Our lead developer, Jennifer, used your files and successfully visualized the data on a Mac. Please refer to the attached screenshot. It seems this issue is specific to Windows 11. In the meantime, we will continue working on Windows to assess the problem and find a solution.

<img width="1396" alt="Screenshot 2024-09-06 at 9 05 18 AM" src="https://github.com/user-attachments/assets/c72c7459-0859-4732-a8a2-1378e7aa4856">

**Comment by evatosco** [comment]
Hi again!

That was so fast, thanks.
I asked a colleague to try the software on her Mac, using the same toy files. You are absolutely right, they do work on Mac.
I look forward to the updates!

Also, since I am already here, would a binary executable file for x86_64 Linux users be possible in the future?
It would make installation easier for some people, for me at least. I have read it is possible to run the current binary for arm64 inside a Docker container. I have not tried it yet. It's not impossible to run, of course, but I was just wondering.

Thank you all and thanks Jennifer, keep up the great work!
Best regards!

**Comment by alperuzun** [comment]
Hi Eva,

We tested the software on Windows 11, and it worked without any errors. In fact, we conducted tests prior to publishing the paper. However, after receiving your message, our team member responsible for the Windows and Linux versions retested the software, and it still worked correctly. We were wondering if you have the appropriate version of Java installed; it should be at least version 1.8. Otherwise, you may encounter issues when running the program. Beyond this, there shouldn't be any other potential causes for the behavior you're experiencing with VGC. Please keep us updates and please let us know if you have any questions or concerns.

Many Thanks
Alper
